/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.abhi.ai;

import java.io.FileNotFoundException;
import java.io.InputStream;
import java.util.Scanner;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import edu.abhi.ai.selection.Selection;
import edu.abhi.ai.selection.SelectionFactory;

public class FeatureSelection {

    private final Logger logger = LogManager.getLogger(FeatureSelection.class);
    private final Scanner console;
    private final SelectionFactory selectionFactory;

    private Knn knn;
    private Input input;

    public FeatureSelection(InputStream inputStream) {
        console = new Scanner(inputStream);
        selectionFactory = new SelectionFactory();
    }

    public void greet() {
        logger.info("Welcome! User");
        logger.info("Welcome to feature selection algorithm made by yours truly");
        logger.info("");
        logger.info("Let's have some fun !!");
    }

    public void knn() {
        logger.info("Type the number of neighbors for vote in kNN : ");
        int k = console.nextInt();
        this.knn = new Knn(k);
    }

    public void read() throws FileNotFoundException {
        logger.info("Type in the path to data file as per project requirements :");
        String path = console.next();
        this.input = new Input(path);
    }

    public void selection() {
        logger.info("Type the option for feature selection algorithm : ");
        logger.info("        1)       ForwardPropagation");
        logger.info("        2)       BackwardElimination");
        int type = console.nextInt();
        Selection selection = selectionFactory.getSelection(type, knn);
        selection.select(input);
    }

    public void close() {
        if (console != null) console.close();
    }

    public static void main(String[] args) throws FileNotFoundException {

        FeatureSelection fs = new FeatureSelection(System.in);

        fs.greet();

        fs.read();

        fs.knn();

        fs.selection();;
        
        fs.close();
    }
}
